project_nico/characters/urls.py
from django.urls import path
from . import views

app_name = 'characters'

urlpatterns = [
    path('creation/', views.CreateCharacterView.as_view(), name='create'),
    path('list/', views.CharactersListView.as_view(), name='list'),
    path('edit/<pk>/', views.CharacterEditView.as_view(), name='edit'),
    path('delete/<pk>/', views.CharacterDeleteView.as_view(), name='delete'),
]

project_nico/project_nico/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', views.HomePage.as_view(), name='home'),
                  path('about', views.AboutView.as_view(), name='about'),
                  path('profile/', views.ProfilePage.as_view(), name='profile'),
                  path('accounts/', include('accounts.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('characters/', include('characters.urls')),
                  path('journal/', include('journal.urls')),
                  path('rpg/', include('rpg.urls'))

              ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

project_nico/rpg/urls.py
from django.urls import path
from . import views

app_name = 'rpg'

urlpatterns = [
    path('', views.RpgView.as_view(), name='rpg'),
    path('battle/<pk>', views.RpgBattleView.as_view(), name='battle'),
    path('instructions/', views.RpgInstructionsView.as_view(), name='instructions'),
]

project_nico/characters/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _


# Race model
class Race(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return self.name


# Class model
class Class(models.Model):
    name = models.CharField(max_length=15)
    description = models.TextField(max_length=100, blank=True)
    power_one = models.ForeignKey('ClassPower', on_delete=models.CASCADE, related_name='attack')
    power_two = models.ForeignKey('ClassPower', on_delete=models.CASCADE, related_name='heal')

    class Meta:
        verbose_name_plural = _("Classes")

    def __str__(self):
        return self.name


# Powers model
class ClassPower(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField(max_length=100, blank=True)
    image = models.ImageField(blank=True)

    def __str__(self):
        return self.name


# Character model
class Character(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=14, unique=True, null=True)
    race = models.ForeignKey('Race', on_delete=models.CASCADE)

    MALE = 'M'
    FEMALE = 'F'
    GENDER_CHOICES = (
        (MALE, 'Male'),
        (FEMALE, 'Female')
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default=MALE)

    def custom_default(self):
        return ('{}.jpg'.format(self.race.name))

    image = models.ImageField(blank=True, default=0)
    char_class = models.ForeignKey('Class', on_delete=models.CASCADE)
    description = models.TextField(max_length=400, blank=True)
    enemy = models.ForeignKey('Enemy', on_delete=models.CASCADE, null=True)

    # Save images according to race gender
    def save(self, *args, **kwargs):

        if self.gender == self.GENDER_CHOICES[0][0]:
            self.image = '{}.jpg'.format(self.race.name.lower())
        else:
            self.image = '{}_female.jpg'.format(self.race.name.lower())

        # Save character name capitalized
        self.name = self.name.capitalize()

        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


# Enemy model
class Enemy(models.Model):
    name = models.CharField(max_length=30)
    image = models.ImageField(blank=True, default=0)

    class Meta:
        verbose_name_plural = _("Enemies")

    def __str__(self):
        return self.name

project_nico/rpg/models.py
from django.db import models

# Create your models here.

project_nico/rpg/views.py
import random

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, ListView, DetailView
from django.apps import apps


# RPG game main page
class RpgView(LoginRequiredMixin, ListView):
    model = apps.get_model('characters', 'Character')
    template_name = 'rpg/rpg_main.html'

    # Return only user data
    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


# RPG combat view
class RpgBattleView(LoginRequiredMixin, DetailView):
    model = apps.get_model('characters', 'Character')
    template_name = 'rpg/rpg_battle.html'

    # Return only user data
    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

    # Call the Enemy class, and return random object from it
    def get_context_data(self, **kwargs):
        context = super(RpgBattleView, self).get_context_data(**kwargs)
        context['enemy'] = (apps.get_model('characters', 'Enemy')).objects.all()[random.randint(0, 6)]
        return context


# RPG instructions view
class RpgInstructionsView(LoginRequiredMixin, TemplateView):
    template_name = 'rpg/rpg_instructions.html'

project_nico/rpg/templates/rpg/rpg_battle.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

    <div id="app">

        <div class="textclass mb-5 rpg-head">
            <a href="{% url 'rpg:instructions' %}" target="_blank"><h1 class="mb-3">Instructions</h1></a>
            <a href="{% url 'rpg:rpg' %}"><h1>Select other character</h1></a>
        </div>

        {# Portraits #}
        <div class="row justify-content-between text-center rounded combat-board textclass  ">

            {# Character info #}
            <div class="col">

                <div class="{{ character.char_class|slugify }}">

                    <div>
                        <img src="{{ character.image.url }}" class="mb-2"
                             alt="Character profile pic"
                             height="200px"
                             width="200px">
                        <h1 style="color: white">{{ character.name }}</h1>
                        <h3>{{ character.char_class }}</h3><br>
                    </div>


                    {# Player Health bar #}
                    <div class="mt-3" style="margin-left: 125px;  ">
                        <div class="progress"
                             style="width: 300px; height: 30px; background-color: rgba(64, 64, 63, 0.7);">
                            <div class="progress-bar bg-danger" role="progressbar"
                                 style="width: 100%; font-family: Arial;"
                                 :style="{width: playerHealth + '%'}"
                                 aria-valuenow="100"
                                 aria-valuemin="0" aria-valuemax="100">HP: [[ playerHealth ]]
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <div class="col" style="border-left: 5px solid darkred">

                {# Enemy info #}
                <div style="margin-bottom: 50px">
                    <img style="margin-bottom: 30px; border: 5px solid grey" src="{{ enemy.image.url }}"
                         alt="Character profile pic"
                         height="200px"
                         width="200px">
                    <h1 style="color: darkred;"><strong>{{ enemy.name }}</strong></h1>
                </div>

                {# Enemy Health bar #}
                <div class="mt-3" style="margin-left: 125px;">
                    <div class="progress" style="width: 300px; height: 30px; background-color: rgba(64, 64, 63, 0.7);"
                    >
                        <div class="progress-bar bg-danger" role="progressbar" style="width: 100%; font-family: Arial"
                             :style="{width: monsterHealth + '%'}"
                             aria-valuenow="100"
                             aria-valuemin="0" aria-valuemax="100">HP: [[ monsterHealth ]]
                        </div>
                    </div>
                </div>
            </div>
        </div>


        {# Spells #}
        <div class="row justify-content-center mb-5">
            <div class="col-4 text-center mt-5">
                <div class="spellbar" v-if="gameIsRunning">

                    {# ATTACK #}
                    <h1 class="mb-2 textclass"><span class="mr-5">Attack</span> <span class="ml-3">Heal</span></h1>
                    <img @click="attack" class="mr-5 btn" data-toggle="tooltip" data-placement="bottom"
                         title="{{ character.char_class.power_one.description }}"
                         src="{{ character.char_class.power_one.image.url }}" style="border: transparent"
                         alt="">


                    {# HEAL #}
                    <img @click="heal" class="ml-5 btn" data-toggle="tooltip" data-placement="bottom"
                         title="{{ character.char_class.power_two.description }}"
                         src="{{ character.char_class.power_two.image.url }}" style="border: transparent"
                         alt="">

                    {# Give up button #}
                    <button class="btn btn-light mt-3" @click="giveUp">Give up</button>
                </div>


                {# Start new game button #}
                <div v-else class="spellbar">
                    <button class="btn btn-outline-success btn-lg mt-3 textclass" @click="startGame">
                        Start new game
                    </button>
                </div>
            </div>
        </div>


        <section class="row log rounded mt-3" v-if="turns.length > 0">

            <div class="col-12">
                <h3 class="textclass text-center mb-3">Combat log</h3>
                <ul>
                    <li v-for="turn in turns"
                        :class="{'player-turn': turn.isPlayer, 'monster-turn': !turn.isPlayer}">
                        [[ turn.text ]]
                    </li>
                </ul>
            </div>
        </section>


    </div>


    <script src="{% static 'project_nico/js/vue.js' %}"></script>
    <script src="{% static 'project_nico/js/rpgbattle.js' %}"></script>
{% endblock %}

project_nico/rpg/templates/rpg/rpg_instructions.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="row mt-5 textclass justify-content-center rowcontent main-menu">
        <div class="col-10">
            <ol>
                <h3>
                    <li>Press 'Start new game' button to display your abilities.</li>
                <li>Each class has it's unique abilities. The left one damages the enemy and the right one heals you.</li>
                <li>When you press an ability, the enemy deals damage to you.</li>
                <li>Whether you win, lose or give up, the page will refresh and we will generate a new random enemy.</li>
                <li>You can see the combat log under the spells bar.</li>
                </h3>

            </ol>

            </ol>

        </div>

    </div>


{% endblock %}

project_nico/rpg/templates/rpg/rpg_main.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

    {% if character_list %}
        <h1 class="textclass text-center mb-5">Select the character you want to play with</h1>

        <div class="row mt-5 justify-content-center">
            {% for character in character_list %}
                <div class="col-4 textclass text-center mb-5">
                    <a href="{% url 'rpg:battle' pk=character.pk %}" style="text-decoration: none;">
                        <div class="{{ character.char_class|slugify }}">
                            <img src="{{ character.image.url }}"
                                 alt="Character profile pic"
                                 height="200px"
                                 width="200px">
                            <h1 style="color: white">{{ character.name }}</h1>
                            <h3>{{ character.char_class }}</h3>
                        </div>
                    </a>
                </div>

            {% endfor %}
        </div>


    {% else %}

        <h1 class="textclass">It seems you don't have any characters yet. <a href="{% url 'characters:create' %}">Go
            ahead and create one!</a></h1>

    {% endif %}

{% endblock %}