project_nico/characters/urls.py
from django.urls import path
from . import views

app_name = 'characters'

urlpatterns = [
    path('creation/', views.CreateCharacterView.as_view(), name='create'),
    path('list/', views.CharactersListView.as_view(), name='list'),
    path('edit/<pk>/', views.CharacterEditView.as_view(), name='edit'),
    path('delete/<pk>/', views.CharacterDeleteView.as_view(), name='delete'),
]

project_nico/journal/urls.py
from django.urls import path
from . import views

app_name = 'journal'

urlpatterns = [
    path('', views.JournalMainView.as_view(), name='journal'),
    path('creation/', views.new_post, name='create'),
    path('entries/', views.PostListView.as_view(), name='entries'),
    path('edit/<pk>/', views.PostEditView.as_view(), name='edit'),
    path('entries/<pk>', views.PostDetailView.as_view(), name='entry-detail'),
    path('delete/<pk>/', views.PostDeleteView.as_view(), name='delete'),
]

project_nico/project_nico/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', views.HomePage.as_view(), name='home'),
                  path('about', views.AboutView.as_view(), name='about'),
                  path('profile/', views.ProfilePage.as_view(), name='profile'),
                  path('accounts/', include('accounts.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('characters/', include('characters.urls')),
                  path('journal/', include('journal.urls')),
                  path('rpg/', include('rpg.urls'))

              ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

project_nico/rpg/urls.py
from django.urls import path
from . import views

app_name = 'rpg'

urlpatterns = [
    path('', views.RpgView.as_view(), name='rpg'),
    path('battle/<pk>', views.RpgBattleView.as_view(), name='battle'),
    path('instructions/', views.RpgInstructionsView.as_view(), name='instructions'),
]

project_nico/characters/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _


# Race model
class Race(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return self.name


# Class model
class Class(models.Model):
    name = models.CharField(max_length=15)
    description = models.TextField(max_length=100, blank=True)
    power_one = models.ForeignKey('ClassPower', on_delete=models.CASCADE, related_name='attack')
    power_two = models.ForeignKey('ClassPower', on_delete=models.CASCADE, related_name='heal')

    class Meta:
        verbose_name_plural = _("Classes")

    def __str__(self):
        return self.name


# Powers model
class ClassPower(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField(max_length=100, blank=True)
    image = models.ImageField(blank=True)

    def __str__(self):
        return self.name


# Character model
class Character(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=14, unique=True, null=True)
    race = models.ForeignKey('Race', on_delete=models.CASCADE)

    MALE = 'M'
    FEMALE = 'F'
    GENDER_CHOICES = (
        (MALE, 'Male'),
        (FEMALE, 'Female')
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default=MALE)

    def custom_default(self):
        return ('{}.jpg'.format(self.race.name))

    image = models.ImageField(blank=True, default=0)
    char_class = models.ForeignKey('Class', on_delete=models.CASCADE)
    description = models.TextField(max_length=400, blank=True)
    enemy = models.ForeignKey('Enemy', on_delete=models.CASCADE, null=True)

    # Save images according to race gender
    def save(self, *args, **kwargs):

        if self.gender == self.GENDER_CHOICES[0][0]:
            self.image = '{}.jpg'.format(self.race.name.lower())
        else:
            self.image = '{}_female.jpg'.format(self.race.name.lower())

        # Save character name capitalized
        self.name = self.name.capitalize()

        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


# Enemy model
class Enemy(models.Model):
    name = models.CharField(max_length=30)
    image = models.ImageField(blank=True, default=0)

    class Meta:
        verbose_name_plural = _("Enemies")

    def __str__(self):
        return self.name

project_nico/journal/models.py
from django.conf import settings
from django.db import models

# Create your models here.

# Journal entry model
class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    character = models.ForeignKey('characters.Character', on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=70)
    text = models.TextField()
    published_date = models.DateTimeField(blank=True, null=True, auto_now=True)

    class Meta:
        ordering = ["-published_date"]

    def __str__(self):
        return self.title

project_nico/journal/forms.py
from django.forms import ModelForm
from .models import Post
from django.apps import apps


# Journal entry form
class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['character', 'title', 'text']

    # Filter only user characters
    def __init__(self, user, *args, **kwargs):
        model = apps.get_model('characters', 'Character')
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['character'].queryset = model.objects.filter(user=user)
        self.fields['text'].label = "Write your tale here"

project_nico/journal/views.py
from django.apps import apps
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import UpdateView, DetailView,  ListView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PostForm
from .models import Post


#Journal main view
class JournalMainView(LoginRequiredMixin, ListView):
    template_name = 'journal/journal_main.html'

    # This is to check if there are characters created
    # Returns a list and check if true in template
    model = apps.get_model('characters', 'Character')

    # Show only user data
    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


# Journal entry creation view
@login_required
def new_post(request):
    if request.method == 'POST':
        form = PostForm(request.user, request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('journal:entries')
    else:
        form = PostForm(request.user)
    return render(request, 'journal/post_form.html', {'form': form})


# Posts list view
class PostListView(LoginRequiredMixin, ListView):
    model = Post
    paginate_by = 50

    # Show only user data
    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


# Post selected view
class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post

    # Show only user data
    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


# Journal entry update View
class PostEditView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'text']
    success_url = reverse_lazy('journal:entries')

    # Show user info only
    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


# Journal entry Delete View
class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('journal:entries')

    # Show user info only
    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

project_nico/journal/templates/journal/journal_main.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block content %}

    <div class="mt-5 textclass text-center">

        <h1>Welcome to your adventure journal!</h1>

        <div class="row mt-5">
            <div class="col-6">

                {# Check if list is empty #}
                {% if character_list|length < 1 %}
                    <a href="{% url 'characters:create' %}">
                        <h1>Create new entry</h1>
                        <h3>(You need to create a character first)</h3>
                    </a>
                {% else %}
                    <a href="{% url 'journal:create' %}">
                        <h1>Create new entry</h1>
                    </a>
                {% endif %}

            </div>
            <div class="col-6">
                <h1><a href="{% url 'journal:entries' %}">View all your posts</a></h1>
            </div>

        </div>

        {# Journal image #}
        <div class="row">
            <div class="col-12">
                <img src="{% static 'project_nico/images/journal.png' %}" alt="">
            </div>
        </div>
    </div>
{% endblock %}

project_nico/journal/templates/journal/post_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <h1 class="mb-5 textclass">A tale of {{ post.character }}</h1>

    {# Character image, name and class-race #}
    <div class="row textclass post rounded">
        <div class="col-3 mycol text-center">
            <img src="{{ post.character.image.url }}" class="mb-3" alt="Character profile pic"
                 height="200px"
                 width="200px">

            <h2>{{ post.character }}</h2>
            <h5>{{ post.character.race }}, {{ post.character.char_class }}</h5>

        </div>

        <div class="col-9">

            {# Title and buttons #}
            <div class="row">
                <div class="col-9">
                    <h1 class="post-text">{{ post.title }} </h1>
                </div>

                {# Edit and delete buttons #}
                <div class="col-3 text-right">
                    {# Edit #}
                    <a href="{% url 'journal:edit' pk=post.pk %}" class="btn btn-warning"><i class="material-icons">
                        edit
                    </i></a>


                    <!-- Button trigger modal -->

                    {# DELETE #}
                    <button type="button" class="btn btn-danger" data-toggle="modal"
                            data-target="#Modal">
                        <i class="material-icons">
                            delete
                        </i>
                    </button>

                    <div class="modal fade text-left mymodal" id="{{ char.name }}Modal" tabindex="-1" role="dialog"
                         aria-labelledby="{{ char.name }}ModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="ModalLabel">
                                        Deleting '{{ post.title }}'</h5>
                                    <button type="button" class="close" data-dismiss="modal"
                                            aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>

                                {# Modal text #}
                                <div class="modal-body">
                                    Are you sure you want to delete '{{ post.title }}' post?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">
                                        Cancel
                                    </button>
                                    <form action="{% url "journal:delete" pk=post.pk %}" method="post">
                                        {% csrf_token %}

                                        <button class="btn btn-danger">Delete
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {# Post text #}
            <h3 class="mt-5 post-text">{{ post.text|linebreaks }}</h3>

            {# Post publication date #}
            <h3 class="mt-5 text-right date">{{ post.published_date }} (UTC)</h3>
        </div>
    </div>
    </div>
{% endblock %}

project_nico/journal/templates/journal/post_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}

    <div class="sub-bg">


        <h1 class="textclass text-center mb-5">Write an entry in your journal about the adventures of any of your
            characters!</h1>

        {# Post form #}
        <div class="row justify-content-center">
            <div class="col-12 postclass rounded border border-danger">
                <form method="POST">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <input type="submit" name="excludeme" class="btn btn-outline-warning btn-lg my-3" value="Add entry">
                </form>
            </div>
        </div>

    </div>

{% endblock %}

project_nico/journal/templates/journal/post_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}

    <div class="mt-5 sub-bg">

        {% if post_list %}

            <h1 class="mb-4 textclass text-center">Here are all your journal entries</h1>

            <div class="text-center mb-5">
                <a href="{% url 'journal:create' %}"><h1 class="btn btn-danger textclass danger-button">Create new
                    entry</h1></a>
            </div>

            {# Posts list #}
            <table class="table table-striped table-dark entry-sumary">
                <thead>
                <tr>
                    <th scope="col">Author</th>
                    <th scope="col">Title</th>
                    <th scope="col">Publication Date</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for post in post_list %}
                    <tr>
                        <th><img src="{{ post.character.image.url }}" alt="Character profile pic" height="50px"
                                 width="50px"><span class="ml-3">{{ post.character }}</span></th>
                        <td><a href="{{ post.pk }}">{{ post.title }}</a></td>
                        <td>{{ post.published_date }} (UTC)</td>
                        <td><a href="{{ post.pk }}" class="btn btn-warning btn-sm mt-2">View post</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <hr>


        {% else %}
            <h1 class="textclass text-center">You haven't written any adventure yet. Go ahead and <a
                    href="{% url 'journal:create' %}">write one!</a></h1>




            {# GATE ANIMATION #} {# GATE ANIMATION #} {# GATE ANIMATION #}
            <div>
                <svg class="gate" style="margin-top: 150px" id="Layer_1" data-name="Layer 1"
                     xmlns="http://www.w3.org/2000/svg"
                     viewBox="0 0 390 536.52"><title>Gate</title>
                    <rect x="0.5" y="0.5" width="39" height="500" style="fill:#333"/>
                    <path d="M669,304V803H631V304h38m1-1H630V804h40V303Z" transform="translate(-630 -303)"
                          style="fill:#333"/>
                    <rect x="70.5" y="0.5" width="39" height="500" style="fill:#333"/>
                    <path d="M739,304V803H701V304h38m1-1H700V804h40V303Z" transform="translate(-630 -303)"
                          style="fill:#333"/>
                    <rect x="140.5" y="0.5" width="39" height="500" style="fill:#333"/>
                    <path d="M809,304V803H771V304h38m1-1H770V804h40V303Z" transform="translate(-630 -303)"
                          style="fill:#333"/>
                    <rect x="210.5" y="0.5" width="39" height="500" style="fill:#333"/>
                    <path d="M879,304V803H841V304h38m1-1H840V804h40V303Z" transform="translate(-630 -303)"
                          style="fill:#333"/>
                    <rect x="280.5" y="0.5" width="39" height="500" style="fill:#333"/>
                    <path d="M949,304V803H911V304h38m1-1H910V804h40V303Z" transform="translate(-630 -303)"
                          style="fill:#333"/>
                    <rect x="350.5" y="0.5" width="39" height="500" style="fill:#333"/>
                    <path d="M1019,304V803H981V304h38m1-1H980V804h40V303Z" transform="translate(-630 -303)"
                          style="fill:#333"/>
                    <rect x="0.5" y="371.5" width="389" height="39" style="fill:#333"/>
                    <path d="M1019,675v38H631V675h388m1-1H630v40h390V674Z" transform="translate(-630 -303)"
                          style="fill:#333"/>
                    <rect x="0.5" y="90.5" width="389" height="39" style="fill:#333"/>
                    <path d="M1019,394v38H631V394h388m1-1H630v40h390V393Z" transform="translate(-630 -303)"
                          style="fill:#333"/>
                    <polygon points="0.85 501.5 39.15 501.5 20 535.5 0.85 501.5" style="fill:#333"/>
                    <path d="M668.29,805,650,837.49,631.71,805h36.58m1.71-1H630l20,35.52L670,804Z"
                          transform="translate(-630 -303)" style="fill:#333"/>
                    <polygon points="70.86 501.5 109.14 501.5 90 535.5 70.86 501.5" style="fill:#333"/>
                    <path d="M738.29,805,720,837.49,701.71,805h36.58m1.71-1H700l20,35.52L740,804Z"
                          transform="translate(-630 -303)" style="fill:#333"/>
                    <polygon points="140.85 501.5 179.15 501.5 160 535.5 140.85 501.5" style="fill:#333"/>
                    <path d="M808.29,805,790,837.49,771.71,805h36.58m1.71-1H770l20,35.52L810,804Z"
                          transform="translate(-630 -303)" style="fill:#333"/>
                    <polygon points="210.85 501.5 249.15 501.5 230 535.5 210.85 501.5" style="fill:#333"/>
                    <path d="M878.29,805,860,837.49,841.71,805h36.58m1.71-1H840l20,35.52L880,804Z"
                          transform="translate(-630 -303)" style="fill:#333"/>
                    <polygon points="280.86 501.5 319.14 501.5 300 535.5 280.86 501.5" style="fill:#333"/>
                    <path d="M948.29,805,930,837.49,911.71,805h36.58m1.71-1H910l20,35.52L950,804Z"
                          transform="translate(-630 -303)" style="fill:#333"/>
                    <polygon points="350.86 501.5 389.14 501.5 370 535.5 350.86 501.5" style="fill:#333"/>
                    <path d="M1018.29,805,1000,837.49,981.71,805h36.58m1.71-1H980l20,35.52L1020,804Z"
                          transform="translate(-630 -303)" style="fill:#333"/>
                </svg>
                <img class="stonearchway" style="margin-top: 300px"
                     src="https://preview.ibb.co/nvHe1e/Stone_Archway.png">

                <div class="forbiddenmessage mt-5">
                    <h3>There's</h3>
                    <h3>nothing here</h3>
                </div>
            </div>

        {% endif %}

    </div>

{% endblock %}