project_nico/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

project_nico/characters/urls.py
from django.urls import path
from . import views

app_name = 'characters'

urlpatterns = [
    path('creation/', views.CreateCharacterView.as_view(), name='create'),
    path('list/', views.CharactersListView.as_view(), name='list'),
    path('edit/<pk>/', views.CharacterEditView.as_view(), name='edit'),
    path('delete/<pk>/', views.CharacterDeleteView.as_view(), name='delete'),
]

project_nico/journal/urls.py
from django.urls import path
from . import views

app_name = 'journal'

urlpatterns = [
    path('', views.JournalMainView.as_view(), name='journal'),
    path('creation/', views.new_post, name='create'),
    path('entries/', views.PostListView.as_view(), name='entries'),
    path('edit/<pk>/', views.PostEditView.as_view(), name='edit'),
    path('entries/<pk>', views.PostDetailView.as_view(), name='entry-detail'),
    path('delete/<pk>/', views.PostDeleteView.as_view(), name='delete'),
]

project_nico/project_nico/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', views.HomePage.as_view(), name='home'),
                  path('about', views.AboutView.as_view(), name='about'),
                  path('profile/', views.ProfilePage.as_view(), name='profile'),
                  path('accounts/', include('accounts.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('characters/', include('characters.urls')),
                  path('journal/', include('journal.urls')),
                  path('rpg/', include('rpg.urls'))

              ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

project_nico/rpg/urls.py
from django.urls import path
from . import views

app_name = 'rpg'

urlpatterns = [
    path('', views.RpgView.as_view(), name='rpg'),
    path('battle/<pk>', views.RpgBattleView.as_view(), name='battle'),
    path('instructions/', views.RpgInstructionsView.as_view(), name='instructions'),
]

project_nico/characters/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _


# Race model
class Race(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return self.name


# Class model
class Class(models.Model):
    name = models.CharField(max_length=15)
    description = models.TextField(max_length=100, blank=True)
    power_one = models.ForeignKey('ClassPower', on_delete=models.CASCADE, related_name='attack')
    power_two = models.ForeignKey('ClassPower', on_delete=models.CASCADE, related_name='heal')

    class Meta:
        verbose_name_plural = _("Classes")

    def __str__(self):
        return self.name


# Powers model
class ClassPower(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField(max_length=100, blank=True)
    image = models.ImageField(blank=True)

    def __str__(self):
        return self.name


# Character model
class Character(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=14, unique=True, null=True)
    race = models.ForeignKey('Race', on_delete=models.CASCADE)

    MALE = 'M'
    FEMALE = 'F'
    GENDER_CHOICES = (
        (MALE, 'Male'),
        (FEMALE, 'Female')
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default=MALE)

    def custom_default(self):
        return ('{}.jpg'.format(self.race.name))

    image = models.ImageField(blank=True, default=0)
    char_class = models.ForeignKey('Class', on_delete=models.CASCADE)
    description = models.TextField(max_length=400, blank=True)
    enemy = models.ForeignKey('Enemy', on_delete=models.CASCADE, null=True)

    # Save images according to race gender
    def save(self, *args, **kwargs):

        if self.gender == self.GENDER_CHOICES[0][0]:
            self.image = '{}.jpg'.format(self.race.name.lower())
        else:
            self.image = '{}_female.jpg'.format(self.race.name.lower())

        # Save character name capitalized
        self.name = self.name.capitalize()

        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


# Enemy model
class Enemy(models.Model):
    name = models.CharField(max_length=30)
    image = models.ImageField(blank=True, default=0)

    class Meta:
        verbose_name_plural = _("Enemies")

    def __str__(self):
        return self.name

project_nico/templates/about.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

    <div class="row" style="color: black; font-family: Arial; background-color: #efefef;">
        <div class="col" style="margin-bottom: 50px">

            {# Spanish #}
            <h1 class="text-center my-5">Español</h1>

            <p>Este sitio fue desarrollado un 90% en Django (Python), Bootstrap (HTML y CSS) y un poco de Vue.js
                para una
                aplicación. No es más que un simple desafío personal con el fin de aprender y a la vez mostrar
                mi
                experiencia y manejo de inglés. La fuente de aprendizaje para crear este blog no es más que internet. No
                hay nadie mas involucrado en la creación de esta página.</p>
            <p>Es una especie de blog personal pero para personajes que el usuario desee crear, con cierta
                variedad de
                opciones libres a elección. A su vez pueden usarse los diferentes personajes creados para jugar
                un mini-juego de
                rol hecho en JavaScript. Si estás en este sitio por primera vez lo más recomdable es recorrerlo en este
                orden: Characters>Journal>Play.</p>
            <p>Soy estudiante de Análisis de Sistemas, cursando segundo año (2019).</p>
            <p>Si estás interesado en mi o mis otros proyectos podes visitar mi <a href="https://github.com/rnbroggi"
                                                                                   target="_blank">GitHub</a>
                o mi
                <a href="https://www.linkedin.com/in/nicol%C3%A1s-broggi-2a4358156/" target="_blank">LinkedIn</a>.
            </p>
            <p>Codigo fuente: <a href="https://github.com/rnbroggi/-NB-Adventure">GitHub</a></p>

            {# English #}
            <h1 class="text-center my-5">English</h1>

            <p>This site was developed 90% in Django Framework (Python), Bootstrap (HTML-CSS) and a little bit of Vue.js
                for one application. It's nothing but a simple personal challenge to learn and show my experience at the
                same time. All knowledge it took me to develop this blog is nothing more than internet. No one else is
                involved in the creation of this site.</p>
            <p>Is a kind of personal blog but for fantasy characters the user can create, with some custom
                options. The characters can also be used to play a rpg mini-game coded in JavaScript. If it's your first
                time in this site, it is recommended you navigate it using this order: Characters>Journal>Play.</p>
            <p>I'm a system analyst student, 2nd year (currently 2019).</p>
            <p>If you are interested in my profile or my other projects you can visit my <a
                    href="https://github.com/rnbroggi" target="_blank">GitHub</a>
                or my
                <a href="https://www.linkedin.com/in/nicol%C3%A1s-broggi-2a4358156/" target="_blank">LinkedIn</a>.
            </p>
            <p>Source code: <a href="https://github.com/rnbroggi/-NB-Adventure">GitHub</a></p>




{% endblock %}

project_nico/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NB Adventure</title>

    {# Tab icon #}
    <link rel="icon" href="{% static 'project_nico/images/n.jpg' %}">

    {# LOAD BOOTSTRAP #}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">


    {# LOAD FONTS AND ICONS #}
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link href="https://fonts.googleapis.com/css?family=MedievalSharp" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Almendra" rel="stylesheet">

    {# LOAD CSS FROM STATIC #}
    <link rel="stylesheet" href="{% static 'project_nico/css/master.css' %}">
    <link rel="stylesheet" href="{% static 'project_nico/css/formstyle.css' %}">
    <link rel="stylesheet" href="{% static 'project_nico/css/character_list_style.css' %}">
    <link rel="stylesheet" href="{% static 'project_nico/css/post_list_style.css' %}">
    <link rel="stylesheet" href="{% static 'project_nico/css/poststyle.css' %}">
    <link rel="stylesheet" href="{% static 'project_nico/css/rpgstyle.css' %}">
</head>

<body class="bg">

<div class="container">

    {# Navbar #}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded-bottom mb-5 ">
        <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'project_nico/images/n.jpg' %}" alt="Brand"
                                                             hight="50px" width="50px"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">


                <a class="nav-item nav-link ml-3" href="{% url 'home' %}">Home </a>

                {% if user.is_authenticated %}

                    {# Items when logged in #}
                    <div class="dropdown characters-class" style="cursor: pointer">
                        <a class="nav-item nav-link ml-3" id="characters-dropdown"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Characters</a>


                        <div class="dropdown-menu" aria-labelledby="characters-dropdown">
                            <a class="dropdown-item" href="{% url 'characters:create' %}">Create new</a>
                            <a class="dropdown-item" href="{% url 'characters:list' %}">My characters</a>
                            <a class="dropdown-item" href="{% url 'journal:entries' %}">My adventures</a>
                        </div>
                    </div>


                    <a class="nav-item nav-link ml-3" href="{% url 'journal:journal' %}">Journal</a>
                    <a class="nav-item nav-link ml-3" href="{% url 'rpg:rpg' %}">Play</a>
                    <a class="nav-item nav-link ml-3" href="{% url 'about' %}">About</a>


                    {# Sign up and Login #}
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Sing up</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
                    <a class="nav-item nav-link" style="margin-left: 650px" href="{% url 'about' %}">About</a>
                {% endif %}


            </div>
        </div>

        {# Profile button #}
        {% if user.is_authenticated %}
            <div class="nav-item nav-link dropdown">
                <button class="btn btn-warning dropdown-toggle btn-lg" type="button" id="dropdownMenuButton"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Welcome, {{ user.username }}
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="{% url 'profile' %}">My profile</a>
                    <a class="dropdown-item" href="{% url 'journal:entries' %}">My posts</a>
                    <a class="dropdown-item" href="{% url 'rpg:rpg' %}">RPG game</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'accounts:logout' %}?next={% url 'home' %}">Logout</a>
                </div>
            </div>
        {% endif %}

    </nav>

    {# Page body #}
    {% block content %}
    {% endblock %}
</div>


</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>

</html>

project_nico/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="">
        {# Carousel #}
        <div class="row">
            <div class="col-12">
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">

                        {# Image 1 #}
                        <div class="carousel-item active">
                            <img class="d-block w-100"
                                 src="{% static 'project_nico/images/carousel/dark_souls.jpeg' %}"
                                 alt="First slide">
                            <div class="carousel-caption d-none d-md-block ds3">
                                <p class="">Slay some enemies to write your stories!</p>
                                <p>A simple but inspiring RPG game</p>
                            </div>
                        </div>

                        {# Image 2 #}
                        <div class="carousel-item">
                            <img class="d-block w-100"
                                 src="{% static 'project_nico/images/carousel/worgen-pirate.jpg' %}"
                                 alt="Second slide">
                            <div class="carousel-caption d-none d-md-block worgen">
                                <p>Create characters with unique power</p>
                                <p>They can be whoever you want</p>
                            </div>
                        </div>

                        {# Image 3 #}
                        <div class="carousel-item">
                            <img class="d-block w-100"
                                 src="{% static 'project_nico/images/carousel/fantasy-book.jpg' %}"
                                 alt="Third slide">
                            <div class="carousel-caption d-none d-md-block book">
                                <p>Write down your own fantasy journal</p>
                                <p>Let your imagination flow along your characters adventures</p>
                            </div>
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button"
                       data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button"
                       data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>

        {# Welcome text #}
        <div class="mt-5 textclass text-center welcome">
            {% if user.is_authenticated %}
                <h1>Hello {{ user.username }}! Are you ready to start a new adventure?</h1>
            {% else %}
                <h1>Hello dear guest! Are you ready to start a new adventure?</h1>
            {% endif %}

            <h1 class="mt-3">Scroll down to explore this land!</h1>
        </div>

        {# Info text #}
        <div class="container">
            <div class="row mt-5 justify-content-center rowcontent main-menu">
                <div class="col-10 textclass text-center">
                    <h1>Have you ever wanted to write your stories as if you were any of your characters?</h1>
                    <h2 class="my-5">Lucky you! NB-Adventure site is your character personal journal!</h2>

                    <p>If you are the kind of person that loves writing little fantasy stories, this shire may help
                        you inspire your adventures. You can create fantasy characters named whatever you want and
                        write their backstory as you please. In NB-Adventure your characters have their own journal
                        where you can write as if you were just one of them</p>
                    <p>First you need to <a
                            href="{% if not user.is_authenticated %}{% url 'accounts:signup' %}{% endif %}">create
                        an account</a>. After you
                        log in you should <a href="

                                {% if user.is_authenticated %}{% url 'characters:create' %}{% else %}{% url 'accounts:signup' %}{% endif %}">create</a>
                        one or many characters.
                        They don't need to be only humans! Why not
                        elves, dwarves or even orcs? You can even choose a class that may fit your stories,
                        such as mages or pirates. Once you created your fantasy character you can open your <a
                                href="
                                        {% if user.is_authenticated %}{% url 'journal:journal' %}{% else %}{% url 'accounts:signup' %}{% endif %}">journal</a>
                        and write
                        posts as if it were handwritten old stories. Well, that was how personal blogs worked centuries
                        ago, right?</p>
                    <p>If you don't feel too inspired, NB-Adventure also offers you a (very) simple turn-based RPG
                        game. Where you can fight and slay different creatures during your journey. So when you are
                        resting after some tough fights you can write down your feats of strength.</p>
                    <p>Well, what are you waiting for fellow writer?

                        {# Link changes if authenticated #}
                        <a href="
                            {% if user.is_authenticated %}
                            {% url 'profile' %}
                            {% else %}
                            {% url 'accounts:signup' %}
                            {% endif %}">Go ahead and start your adventure!</a></p>


                </div>
            </div>
        </div>
    </div>

    {# Footer #}
    <footer class="full-width">
        <div class="row text-center mr-5">
            <div class="col">
                <p><a href="https://github.com/rnbroggi" target="_blank"><i>By Nicolás Broggi</i></a></p>
            </div>
        </div>
        <div class="row text-center">
            <div class="container">
                <div class="col">
                    <img src="https://www.tpsistemas.com/web/image/1127/python-django-logo-128x128.png" height="128"
                         width="128px" alt="">
                    <img src="https://www.drupal.org/files/project-images/bootstrap-stack.png" width="128px"
                         height="128px"
                         alt="">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Vue.js_Logo_2.svg/1200px-Vue.js_Logo_2.svg.png"
                         width="128px" height="128px" alt="">
                </div>
            </div>
        </div>
    </footer>
{% endblock %}

project_nico/templates/profile.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}

    {% block profiledata %}

        <div class="my-5 textclass">

            <h1 class="mb-3">Profile Information</h1>
            <h3>Username: {{ user.username }}</h3>
            <h3>Email: {{ user.email }}</h3>

        </div>


    {% endblock %}

    {% if character_list %}
        <h1 class="mb-5 textclass text-center">My characters:</h1>

        {% for char in character_list %}

            {# Character image and name #}
            <div class="row all-characters rounded textclass">
                <div class="col-2 {{ char.char_class|slugify }}"><img src="{{ char.image.url }}"
                                        alt="Character profile pic"
                                        height="140px"
                                        width="140px">
                    <p class="text-center textclass">{{ char.name }}</p>
                </div>

                {# Character information #}
                <div class="col-8 chardata">
                    <p>{{ char.race }}</p>
                    <p></p>
                    <p class="{{ char.char_class|slugify }}">{{ char.char_class }}</p>
                    {% if char.description %}
                        <p>{{ char.description|linebreaks }}</p>
                    {% else %}
                        <p>(No description)</p>
                    {% endif %}
                </div>

                {# Edit and Delete buttons #}
                <div class="col-2 align-self-start">
                    {# EDIT #}
                    <a href="{% url 'characters:edit' pk=char.pk %}" class="btn btn-warning">Edit</a>

                    {# DELETE #}
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-danger" data-toggle="modal"
                            data-target="#{{ char.name }}Modal">
                        Delete
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="{{ char.name }}Modal" tabindex="-1" role="dialog"
                         aria-labelledby="{{ char.name }}ModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">

                                    {# Modal title #}
                                    <h5 class="modal-title" id="{{ char.name }}ModalLabel">
                                        Deleting {{ char.name }}</h5>
                                    <button type="button" class="close" data-dismiss="modal"
                                            aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>

                                {# Modal body #}
                                <div class="modal-body">
                                    Are you sure you want to delete {{ char.name }}? All data and progress
                                    will be
                                    lost
                                </div>

                                {# Confirmation buttons #}
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">
                                        Cancel
                                    </button>
                                    <form action="{% url "characters:delete" pk=char.pk %}" method="post">
                                        {% csrf_token %}

                                        <button class="btn btn-danger">Delete
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <hr>
        {% endfor %}
        </div>
    {% else %}
        <h2 class="textclass text-center">You have no characters yet. Go ahead and <a
                href="{% url 'characters:create' %}">create a new one!</a>
        </h2>

        {% block gate %}
        {% endblock %}
    {% endif %}

{% endblock %}